{{- range $key, $value := .Values.applications -}}
{{- $disabled := false}}
{{- $server := "https://kubernetes.default.svc" }}
{{- $path := $key }}
{{- $source := false }}
{{- $disableAutoSync := false }}
{{- $automatedPrune := true }}
{{- $selfHeal := true }}
{{- if . }}
{{- $disabled = .disabled -}}
{{- $server = .server -}}
{{- $path = .path -}}
{{- $source = .source -}}
{{- $disableAutoSync = .disableAutoSync -}}
{{- end -}}
{{- if not $disabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: {{ default "argocd" $.Values.argocdNamespace }}
spec:
  destination:
    namespace: {{ default $key $path }}
    server: {{ default  $server }}
  project: {{ $.Release.Name }}
  source:
    path: {{ $path }}
    repoURL: {{ $.Values.repository }}
{{ if $source }}
{{- toYaml $source | indent 6 }}
{{- end }}
{{ if not $disableAutoSync }}
  syncPolicy:
    automated:
      prune: {{ default true $automatedPrune }}
      selfHeal: {{ default true $selfHeal }}
{{- end }}
{{- end }}
{{ end }}