repository: https://github.com/baloise-incubator/okd4-cluster-config.git
#argocdNamespace: "argocd"
#server: "https://kubernetes.default.svc"
namespace:
  annotations: {}
  labels: {}

enableDefaultNetworkPolicy: false
enableDefaultLimitRange: true
allowAllNamespaces: true

roleBindings:
#  - groupName: "team1"
#    clusterRoleName: "admin"

clusterResourceWhitelist:
  - group: '*'
    kind: '*'

namespaceResourceBlacklist:
#  - group: 'apps'
#    kind: 'DaemonSet'

applications:
  argocd: {}
  cluster-resources:
    source:
      directory:
        recurse: true
  sealed-secrets: {}
  tekton-chatopshandler:
    disableAutoSync: true