# This is a basic workflow to help you get started with Actions

name: sync-apps

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync-apps:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Run gitopscli Container
      run: |
        docker run --rm baloise/gitopscli:5.8.1 sync-apps \
          --git-provider github
          --username ${{ secrets.GIT_USERNAME }} \
          --password ${{ secrets.GIT_TOKEN }} \
          --organisation baloise-incubator \
          --repository-name okd4-gitops-demo \
          --root-organisation baloise-incubator \
          --root-repository-name okd4-apps-root-config
